<?php
/**
 * ApiException
 * PHP version 5
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero oAuth 2 identity service
 *
 * This specifing endpoints related to managing authentication tokens and identity for Xero API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.0.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace XeroAPI\XeroPHP;

use \Exception;

/**
 * ApiException Class Doc Comment
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ApiException extends Exception
{

    /**
     * The HTTP body of the server response either as Json or string.
     *
     * @var mixed
     */
    protected $responseBody;

    /**
     * The HTTP header of the server response.
     *
     * @var string[]|null
     */
    protected $responseHeaders;

    /**
     * The deserialized response object
     *
     * @var $responseObject;
     */
    protected $responseObject;

    /**
     * Constructor
     *
     * @param string          $message         Error message
     * @param int             $code            HTTP status code
     * @param string[]|null   $responseHeaders HTTP response header
     * @param mixed           $responseBody    HTTP decoded body of the server response either as \stdClass or string
     * @param \Throwable|null $previous        Originating exception, if any
     */
    public function __construct($message = "", $code = 0, $responseHeaders = [], $responseBody = null, ?\Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);
        $this->responseHeaders = $responseHeaders;
        $this->responseBody = $responseBody;
    }

    /**
     * Creates an API exception from a Guzzle request failure.
     *
     * Connection failures do not have an HTTP response. Treat those as status
     * code zero instead of dereferencing a null response in async callbacks.
     * The originating exception is kept as the previous exception so a cURL
     * timeout, a DNS failure, a TLS handshake failure and a refused connection
     * stay distinguishable, since none of them carry a status code or body.
     *
     * @param mixed $exception Guzzle request exception
     *
     * @return self
     */
    public static function fromRequestException($exception)
    {
        $response = method_exists($exception, 'getResponse') ? $exception->getResponse() : null;
        $request = method_exists($exception, 'getRequest') ? $exception->getRequest() : null;
        $statusCode = $response ? $response->getStatusCode() : 0;
        $uri = self::safeRequestUri($request, $response !== null);

        return new self(
            sprintf('[%d] Error connecting to the API (%s)', $statusCode, $uri),
            $statusCode,
            $response ? $response->getHeaders() : [],
            $response ? $response->getBody() : null,
            $exception instanceof \Throwable ? $exception : null
        );
    }

    /**
     * Returns a bounded request URI without userinfo, query or fragment.
     *
     * A failure that carries an HTTP response keeps its path, so the failing
     * endpoint stays identifiable and the message matches the synchronous
     * path. A transport failure has no response and no meaningful endpoint,
     * so only the origin is reported.
     *
     * @param mixed $request     HTTP request, if available
     * @param bool  $includePath Whether to keep the request path
     *
     * @return string
     */
    private static function safeRequestUri($request, $includePath)
    {
        if (!$request || !method_exists($request, 'getUri')) {
            return 'unknown URI';
        }
        $uri = $request->getUri();
        if (!method_exists($uri, 'getHost') || $uri->getHost() === '') {
            return 'unknown URI';
        }
        $uri = $uri
            ->withUserInfo('')
            ->withQuery('')
            ->withFragment('');
        if ($includePath) {
            $withPath = self::boundedUri((string) $uri);
            if ($withPath !== null) {
                return $withPath;
            }
        }
        $origin = self::boundedUri((string) $uri->withPath(''));
        return $origin === null ? 'unknown URI' : $origin;
    }

    /**
     * Returns the URI when it is short and printable, otherwise null.
     *
     * @param string $uri Candidate URI
     *
     * @return string|null
     */
    private static function boundedUri($uri)
    {
        if (strlen($uri) > 256 || !preg_match('/^[\x21-\x7e]+$/D', $uri)) {
            return null;
        }
        return $uri;
    }

    /**
     * Gets the HTTP response header
     *
     * @return string[]|null HTTP response header
     */
    public function getResponseHeaders()
    {
        return $this->responseHeaders;
    }

    /**
     * Gets the HTTP body of the server response either as Json or string
     *
     * @return mixed HTTP body of the server response either as \stdClass or string
     */
    public function getResponseBody()
    {
        return $this->responseBody;
    }

    /**
     * Sets the deseralized response object (during deserialization)
     *
     * @param mixed $obj Deserialized response object
     *
     * @return void
     */
    public function setResponseObject($obj)
    {
        $this->responseObject = $obj;
    }

    /**
     * Gets the deseralized response object (during deserialization)
     *
     * @return mixed the deserialized response object
     */
    public function getResponseObject()
    {
        return $this->responseObject;
    }
}
