<?php
/**
 * ProblemType
 *
 * PHP version 5
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Finance API
 *
 * The Finance API is a collection of endpoints which customers can use in the course of a loan application, which may assist lenders to gain the confidence they need to provide capital.
 *
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace XeroAPI\XeroPHP\Models\Finance;
use \XeroAPI\XeroPHP\FinanceObjectSerializer;
use \XeroAPI\XeroPHP\StringUtil;
/**
 * ProblemType Class Doc Comment
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProblemType
{
    /**
     * Possible values of this enum
     */
    const NOT_SET = 'NotSet';
    const INVALID_REQUEST = 'invalid-request';
    const INVALID_APPLICATION = 'invalid-application';
    const SERVICE_UNAVAILABLE = 'service-unavailable';
    const INTERNAL_ERROR = 'internal-error';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::NOT_SET,
            self::INVALID_REQUEST,
            self::INVALID_APPLICATION,
            self::SERVICE_UNAVAILABLE,
            self::INTERNAL_ERROR,
        ];
    }
}


