<?php
/**
 * Contracts
 *
 * PHP version 5
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Payroll UK
 *
 * This is the Xero Payroll API for orgs in the UK region.
 *
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace XeroAPI\XeroPHP\Models\PayrollUk;

use \ArrayAccess;
use \XeroAPI\XeroPHP\PayrollUkObjectSerializer;
use \XeroAPI\XeroPHP\StringUtil;
use ReturnTypeWillChange;

/**
 * Contracts Class Doc Comment
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Contracts implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Contracts';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'start_date' => '\DateTime',
        'employment_status' => '\XeroAPI\XeroPHP\Models\PayrollUk\EmploymentStatus',
        'contract_type' => '\XeroAPI\XeroPHP\Models\PayrollUk\ContractType',
        'public_key' => 'string',
        'is_fixed_term' => 'bool',
        'fixed_term_end_date' => '\DateTime',
        'developmental_role_details' => '\XeroAPI\XeroPHP\Models\PayrollUk\DevelopmentalRoleDetails'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'start_date' => 'date',
        'employment_status' => null,
        'contract_type' => null,
        'public_key' => 'uuid',
        'is_fixed_term' => null,
        'fixed_term_end_date' => 'date',
        'developmental_role_details' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'start_date' => 'startDate',
        'employment_status' => 'employmentStatus',
        'contract_type' => 'contractType',
        'public_key' => 'publicKey',
        'is_fixed_term' => 'isFixedTerm',
        'fixed_term_end_date' => 'fixedTermEndDate',
        'developmental_role_details' => 'developmentalRoleDetails'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'start_date' => 'setStartDate',
        'employment_status' => 'setEmploymentStatus',
        'contract_type' => 'setContractType',
        'public_key' => 'setPublicKey',
        'is_fixed_term' => 'setIsFixedTerm',
        'fixed_term_end_date' => 'setFixedTermEndDate',
        'developmental_role_details' => 'setDevelopmentalRoleDetails'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'start_date' => 'getStartDate',
        'employment_status' => 'getEmploymentStatus',
        'contract_type' => 'getContractType',
        'public_key' => 'getPublicKey',
        'is_fixed_term' => 'getIsFixedTerm',
        'fixed_term_end_date' => 'getFixedTermEndDate',
        'developmental_role_details' => 'getDevelopmentalRoleDetails'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['start_date'] = isset($data['start_date']) ? $data['start_date'] : null;
        $this->container['employment_status'] = isset($data['employment_status']) ? $data['employment_status'] : null;
        $this->container['contract_type'] = isset($data['contract_type']) ? $data['contract_type'] : null;
        $this->container['public_key'] = isset($data['public_key']) ? $data['public_key'] : null;
        $this->container['is_fixed_term'] = isset($data['is_fixed_term']) ? $data['is_fixed_term'] : null;
        $this->container['fixed_term_end_date'] = isset($data['fixed_term_end_date']) ? $data['fixed_term_end_date'] : null;
        $this->container['developmental_role_details'] = isset($data['developmental_role_details']) ? $data['developmental_role_details'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['start_date'] === null) {
            $invalidProperties[] = "'start_date' can't be null";
        }
        if ($this->container['employment_status'] === null) {
            $invalidProperties[] = "'employment_status' can't be null";
        }
        if ($this->container['contract_type'] === null) {
            $invalidProperties[] = "'contract_type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets start_date
     *
     * @return \DateTime
     */
    public function getStartDate()
    {
        return $this->container['start_date'];
    }

    /**
     * Sets start_date
     *
     * @param \DateTime $start_date The contract start date of the employee. This will be locked once an employee has been paid and cannot be changed (YYYY-MM-DD)
     *
     * @return $this
     */
    public function setStartDate($start_date)
    {

        $this->container['start_date'] = $start_date;

        return $this;
    }



    /**
     * Gets employment_status
     *
     * @return \XeroAPI\XeroPHP\Models\PayrollUk\EmploymentStatus
     */
    public function getEmploymentStatus()
    {
        return $this->container['employment_status'];
    }

    /**
     * Sets employment_status
     *
     * @param \XeroAPI\XeroPHP\Models\PayrollUk\EmploymentStatus $employment_status employment_status
     *
     * @return $this
     */
    public function setEmploymentStatus($employment_status)
    {

        $this->container['employment_status'] = $employment_status;

        return $this;
    }



    /**
     * Gets contract_type
     *
     * @return \XeroAPI\XeroPHP\Models\PayrollUk\ContractType
     */
    public function getContractType()
    {
        return $this->container['contract_type'];
    }

    /**
     * Sets contract_type
     *
     * @param \XeroAPI\XeroPHP\Models\PayrollUk\ContractType $contract_type contract_type
     *
     * @return $this
     */
    public function setContractType($contract_type)
    {

        $this->container['contract_type'] = $contract_type;

        return $this;
    }



    /**
     * Gets public_key
     *
     * @return string|null
     */
    public function getPublicKey()
    {
        return $this->container['public_key'];
    }

    /**
     * Sets public_key
     *
     * @param string|null $public_key The public key of the contract. Public key is required if the intention is to edit an existing contract. If no key is supplied a new contract will be created
     *
     * @return $this
     */
    public function setPublicKey($public_key)
    {

        $this->container['public_key'] = $public_key;

        return $this;
    }



    /**
     * Gets is_fixed_term
     *
     * @return bool|null
     */
    public function getIsFixedTerm()
    {
        return $this->container['is_fixed_term'];
    }

    /**
     * Sets is_fixed_term
     *
     * @param bool|null $is_fixed_term describes whether the contract is fixed term (required if trying to create Fixed term contract)
     *
     * @return $this
     */
    public function setIsFixedTerm($is_fixed_term)
    {

        $this->container['is_fixed_term'] = $is_fixed_term;

        return $this;
    }



    /**
     * Gets fixed_term_end_date
     *
     * @return \DateTime|null
     */
    public function getFixedTermEndDate()
    {
        return $this->container['fixed_term_end_date'];
    }

    /**
     * Sets fixed_term_end_date
     *
     * @param \DateTime|null $fixed_term_end_date The fixed term end date of the employee. Not required if isFixedTerm is false or not provided (required if trying to create Fixed term contract)
     *
     * @return $this
     */
    public function setFixedTermEndDate($fixed_term_end_date)
    {

        $this->container['fixed_term_end_date'] = $fixed_term_end_date;

        return $this;
    }



    /**
     * Gets developmental_role_details
     *
     * @return \XeroAPI\XeroPHP\Models\PayrollUk\DevelopmentalRoleDetails|null
     */
    public function getDevelopmentalRoleDetails()
    {
        return $this->container['developmental_role_details'];
    }

    /**
     * Sets developmental_role_details
     *
     * @param \XeroAPI\XeroPHP\Models\PayrollUk\DevelopmentalRoleDetails|null $developmental_role_details developmental_role_details
     *
     * @return $this
     */
    public function setDevelopmentalRoleDetails($developmental_role_details)
    {

        $this->container['developmental_role_details'] = $developmental_role_details;

        return $this;
    }


    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            PayrollUkObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }
}


