<?php
/**
 * NICategoryLetter
 *
 * PHP version 5
 *
 * @category Class
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Xero Payroll UK
 *
 * This is the Xero Payroll API for orgs in the UK region.
 *
 * Contact: api@xero.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.4.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace XeroAPI\XeroPHP\Models\PayrollUk;
use \XeroAPI\XeroPHP\PayrollUkObjectSerializer;
use \XeroAPI\XeroPHP\StringUtil;
use ReturnTypeWillChange;

/**
 * NICategoryLetter Class Doc Comment
 *
 * @category Class
 * @description The employee&#39;s NI Category letter.
 * @package  XeroAPI\XeroPHP
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class NICategoryLetter
{
    /**
     * Possible values of this enum
     */
    const A = 'A';
    const B = 'B';
    const C = 'C';
    const D = 'D';
    const E = 'E';
    const F = 'F';
    const H = 'H';
    const I = 'I';
    const J = 'J';
    const K = 'K';
    const L = 'L';
    const M = 'M';
    const N = 'N';
    const S = 'S';
    const V = 'V';
    const X = 'X';
    const Z = 'Z';
    
    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::A,
            self::B,
            self::C,
            self::D,
            self::E,
            self::F,
            self::H,
            self::I,
            self::J,
            self::K,
            self::L,
            self::M,
            self::N,
            self::S,
            self::V,
            self::X,
            self::Z,
        ];
    }
}


