name: PHP Build, Lint

on:
    push:

jobs:
    build-test-lint:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout xero-php repo
              uses: actions/checkout@v4
              with:
                repository: XeroAPI/xero-php-oauth2
                path: xero-php-oauth2

            - name: Setup PHP
              run: sudo apt-get install -y php php-mbstring php-intl php-xml php-zip php-curl

            - name: Install Composer
              run: |
                php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
                php composer-setup.php --install-dir=/usr/local/bin --filename=composer
                php -r "unlink('composer-setup.php');"

            - name: Install Dependencies
              run: composer install
              working-directory: xero-php-oauth2

            - name: Validate PHP Syntax
              run: find . -path ./vendor -prune -o -name "*.php" -exec php -l {} \; > /dev/null || exit 1
              working-directory: xero-php-oauth2