name: Check Packagist Publish

on:
 pull_request:
    branches:
        - master

jobs:
  check-publish:
     runs-on: ubuntu-latest
    
     steps:

        - name: Checkout repo
          uses: actions/checkout@v4
          with:
           repository: XeroAPI/xero-php-oauth2
           path: xero-php-oauth2

        - name: Fetch Latest release number
          id: get_latest_release_number
          run: |
            latest_version=$(gh release view --json tagName --jq '.tagName')
            echo "Latest release version is - $latest_version"
            echo "php_version=${latest_version}" >> $GITHUB_ENV
          working-directory: xero-php-oauth2
          env:
           GH_TOKEN: ${{secrets.GITHUB_TOKEN}}

        - name: Get latest version from packgist
          id: get_packagist_version
          run: |
           RESPONSE=$(curl -s https://repo.packagist.org/p2/xeroapi/xero-php-oauth2.json)
           LATEST_VERSION=$(echo $RESPONSE | jq -r '.packages["xeroapi/xero-php-oauth2"][0].version')
           echo "latest packagist version $LATEST_VERSION"
           echo "latest_packagist_version=${LATEST_VERSION}" >> $GITHUB_ENV

        - name: Compare versions
          id: compare_versions
          run: |
            if [ "${{env.php_version}}" == "${{env.latest_packagist_version}}" ]; then
             echo "Packagist is up-to-date"
             echo "packagist_status=success" >> $GITHUB_ENV
            else
             echo "Packgist is not updated yet"
             echo "packagist_status=failure" >> $GITHUB_ENV
            fi

      #   - name: Send slack Notification on Success
      #     if: ${{ env.packagist_status == 'success' }}
      #     uses:
